# Generated by Django 3.2.10 on 2023-01-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='no_of_like',
            new_name='_no_of_like',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='no_of_unlike',
            new_name='_no_of_unlike',
        ),
    ]
