# Generated by Django 3.2.10 on 2023-01-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230114_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='_no_of_like',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='_no_of_unlike',
        ),
    ]
