# Generated by Django 3.2.10 on 2023-01-25 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230115_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blog',
            name='modified_date',
            field=models.DateField(auto_created=True, default=None, null=True),
        ),
    ]
