# Generated by Django 3.2.10 on 2023-01-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230125_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='modified_date',
            field=models.DateField(auto_created=True, blank=True, default=None, null=True),
        ),
    ]
