# Generated by Django 3.2.10 on 2023-02-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='media/image/default.jpg', upload_to='media/image'),
        ),
    ]
